version: '3.8'

services:
  app:
    build: .
    ports:
      - "11201:11201"
    container_name: spectra-mapban
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules